### ISSUE TITLE
Failed to start gpustack while os info includes Chinese

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#111]
**Describe the bug**

Failed to start gpustack while os info includes Chinese

**Steps to reproduce**
1. Query windows os info, found it includes Chinese
2. Then install the GPUStack
3. Below error occurred

```
2024-07-30T13:46:54+08:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-07-30T13:46:54+08:00 - gpustack.server.server - INFO - Running database migration.
2024-07-30T13:46:54+08:00 - gpustack.server.server - INFO - Database migration completed.
2024-07-30T13:46:55+08:00 - gpustack.server.server - INFO - Generated initial admin password. You can get it from C:\Users\Tina\AppData\Roaming\gpustack\initial_admin_password.
2024-07-30T13:46:55+08:00 - gpustack.server.server - INFO - Serving on 0.0.0.0:80.
2024-07-30T13:46:56+08:00 - gpustack.worker.worker - INFO - Starting GPUStack worker.
2024-07-30T13:46:56+08:00 - gpustack.worker.worker - INFO - Serving worker APIs on 0.0.0.0:10150.
Exception in thread Thread-7 (_readerthread):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-6 (_readerthread):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python310\lib\subprocess.py", line 1515, in _readerthread
    self._target(*self._args, **self._kwargs)
  File "C:\Python310\lib\subprocess.py", line 1515, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 3463: illegal multibyte sequence
2024-07-30T13:46:56+08:00 - gpustack.worker.worker_manager - ERROR - Failed to initialize worker: Failed to execute ['C:\\Users\\Tina\\pipx\\venvs\\gpustack\\lib\\site-packages\\gpustack\\third_party\\bin\\fastfetch\\fastfetch-windows-amd64.exe', '--gpu-driver-specific', 'true', '--gpu-temp', 'true', '--format', 'json', '--config', 'C:\\Users\\Tina\\pipx\\venvs\\gpustack\\lib\\site-packages\\gpustack\\third_party\\config\\fastfetch\\config.jsonc']: 'NoneType' object has no attribute 'splitlines'
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 3461: illegal multibyte sequence
2024-07-30T13:46:56+08:00 - gpustack.worker.exporter - ERROR - Failed to get worker node status for metrics exporter: Failed to execute ['C:\\Users\\Tina\\pipx\\venvs\\gpustack\\lib\\site-packages\\gpustack\\third_party\\bin\\fastfetch\\fastfetch-windows-amd64.exe', '--gpu-driver-specific', 'true', '--gpu-temp', 'true', '--format', 'json', '--config', 'C:\\Users\\Tina\\pipx\\venvs\\gpustack\\lib\\site-packages\\gpustack\\third_party\\config\\fastfetch\\config.jsonc']: 'NoneType' object has no attribute 'splitlines'
2024-07-30T13:46:56+08:00 - gpustack.worker.exporter - INFO - Serving metric exporter on 0.0.0.0:10151.
Exception in thread Thread-10 (_readerthread):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python310\lib\subprocess.py", line 1515, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 3461: illegal multibyte sequence
```

**Result**

**Expected behavior**

**Environment**

- GPUStack version:
- OS:
- GPU:

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(8d7b01f)
- OS: Windows 10 Professional
- GPU: NVIDIA GeForce RTX 4090 24G 
```
Subprocess Standard Output:
Preferred Encoding (locale): cp936
Default String Encoding (sys): utf-8
Standard Output Encoding (sys.stdout): gbk
Standard Input Encoding (sys.stdin): utf-8
Standard Error Encoding (sys.stderr): gbk
File System Encoding (sys): utf-8
```

**Test Result:** pass
```
2024-08-01T16:27:01+08:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-08-01T16:27:01+08:00 - gpustack.server.server - INFO - Running database migration.
2024-08-01T16:27:01+08:00 - gpustack.server.server - INFO - Database migration completed.
2024-08-01T16:27:01+08:00 - gpustack.server.server - INFO - Serving on 0.0.0.0:80.
2024-08-01T16:27:02+08:00 - gpustack.worker.worker - INFO - Starting GPUStack worker.
2024-08-01T16:27:02+08:00 - gpustack.worker.worker - INFO - Serving worker APIs on 0.0.0.0:10150.
2024-08-01T16:27:02+08:00 - gpustack.worker.worker_manager - INFO - Registering worker: DESKTOP-H2LG9AC
2024-08-01T16:27:02+08:00 - gpustack.worker.exporter - INFO - Serving metric exporter on 0.0.0.0:10151.
2024-08-01T16:27:02+08:00 - gpustack.worker.worker_manager - INFO - Worker DESKTOP-H2LG9AC registered.
2024-08-01T16:28:58+08:00 - gpustack.scheduler.calculator - INFO - Calculating resource claim for model instance llama3.1-Wf5dO
2024-08-01T16:29:15+08:00 - gpustack.scheduler.calculator - INFO - Calculated resource claim for model instance llama3.1-Wf5dO, least: memoryEstimate(offloadLayers=0, uma=memoryResource(ram=1170337112, vram=0), nonUMA=memoryResource(ram=1327623512, vram=964157440)), most: memoryEstimate(offloadLayers=33, uma=memoryResource(ram=88206680, vram=1073741824), nonUMA=memoryResource(ram=245493080, vram=5964816384))
2024-08-01T16:29:15+08:00 - gpustack.worker.serve_manager - INFO - Start serving model instance llama3.1-Wf5dO on port 40291
```
