### ISSUE TITLE
 Failed to start GPUStack on Windows: module 'os' has no attribute 'uname'

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#159]
**Describe the bug**

Failed to start GPUStack on Windows.

**Steps to reproduce**

1. Using installation script to run GPUStack.

**Result**

1. Failed to start.
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\seal\pipx\venvs\gpustack\Scripts\gpustack.exe\__main__.py", line 4, in <module>
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\main.py", line 5, in <module>
    from gpustack.cmd import setup_start_cmd
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\cmd\__init__.py", line 1, in <module>
    from .start import setup_start_cmd
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\cmd\start.py", line 12, in <module>
    from gpustack.worker.worker import Worker
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\worker\__init__.py", line 1, in <module>
    from .worker import Worker
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\worker\worker.py", line 18, in <module>
    from gpustack.worker.serve_manager import ServeManager
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\worker\serve_manager.py", line 16, in <module>
    from gpustack.worker.inference_server import InferenceServer
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\worker\inference_server.py", line 19, in <module>
    from gpustack.worker.downloaders import HfDownloader, OllamaLibraryDownloader
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\worker\downloaders.py", line 119, in <module>
    class OllamaLibraryDownloader:
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\gpustack\worker\downloaders.py", line 122, in OllamaLibraryDownloader
    _user_agent = f"ollama/0.3.3 ({os.uname().machine} {os.uname().sysname}) Go/1.22.0"
                                   ^^^^^^^^
AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?
```

**Expected behavior**

**Environment**

- GPUStack version: main(bb7f860)
- OS: Windows 11
- GPU: NVIDIA GeForce RTX 4090 24G 

**Additional context**

**Comment by Finenyaco** [comment]
Verified in main 6cc9fee.
