### ISSUE TITLE
Installation script error due to misconfigured parameters during upgrade on Windows

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#162]
**Describe the bug**

Script error due to misconfigured parameters during upgrade on Windows

**Steps to reproduce**

1. Using the script to install GPUStack.
2. Using the script to update the configuration, but configure an incorrect parameter `-port 8080`.

**Result**

1. The installation script returned errors.
```
PS C:\Windows\system32> Invoke-Expression "& { $((Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/gpustack/gpustack/main/install.ps1' -UseBasicParsing).Content) } -port 8080"
[INFO] Chocolatey already installed.
[INFO] Python already installed.
[INFO] Pipx already installed.
[INFO] NSSM already installed.
[INFO] GPUStack already installed, Upgrading...
[INFO] Upgrade GPUStack...
[INFO] Upgrade GPUStack with --pip-args=--pre gpustack
[INFO] Check pipx environment...
[INFO] Upgrade GPUStack with pipx and pythin C:\Python310\python.exe...
[INFO] Uninstall existing gpustack...
[INFO] Stopping existing GPUStack service...
[INFO] Stopped existing GPUStack success
[INFO] Removed existing GPUStack success
Failed to delete C:\Users\seal\pipx\venvs\gpustack. Will move it to a temp folder to delete later.
uninstalled gpustack! ✨ 🌟 ✨
pipx >(setup:1083): pipx version is 1.6.0
pipx >(setup:1084): Default python interpreter is 'C:\Python310\python.exe'
pipx >(rmdir:56): removing directory C:\Users\seal\pipx\trash
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\pipx.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\pipx\main.py", line 1144, in cli
    setup(parsed_pipx_args)
  File "C:\Python310\lib\site-packages\pipx\main.py", line 1108, in setup
    rmdir(paths.ctx.trash, False)
  File "C:\Python310\lib\site-packages\pipx\util.py", line 61, in rmdir
    shutil.rmtree(path, ignore_errors=safe_rm)
  File "C:\Python310\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 4 more times]
  File "C:\Python310\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python310\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\seal\\pipx\\trash\\hzyejrvx.gpustack\\Lib\\site-packages\\gpustack\\third_party\\bin\\llama-box\\llama-box-windows-amd64-cuda-12.5.exe'
```

2. If the same parameters are used during the first installation, there will be no error; the parameter will be ignored.

**Expected behavior**

**Environment**

- GPUStack version: v0.1.1rc1
- OS: Windows 11
- GPU: NVIDIA GeForce RTX 4090 24G 

**Additional context**

**Comment by linyinli** [comment]
Closing as won’t fix since https://github.com/gpustack/gpustack/issues/2348 deprecates this method.
