### ISSUE TITLE
Dashboard response 500 when the worker has no GPU

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#172]
**Describe the bug**

**Steps to reproduce**

1. Prevent the host from using NVIDIA GPUs.
2. Go to the dashboard.

```
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:2685] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device [1043:8984]
	Flags: bus master, fast devsel, latency 0, IRQ 11, IOMMU group 15
	Memory at 92000000 (32-bit, non-prefetchable) [size=16M]
	Memory at 80000000 (64-bit, prefetchable) [size=256M]
	Memory at 90000000 (64-bit, prefetchable) [size=32M]
	I/O ports at 5000 [size=128]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: vfio-pci
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

01:00.1 Audio device [0403]: NVIDIA Corporation Device [10de:22ba] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device [1043:8984]
	Flags: bus master, fast devsel, latency 0, IRQ 10, IOMMU group 15
	Memory at 93080000 (32-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: vfio-pci
	Kernel modules: snd_hda_intel
```

**Result**

1. Returned error code 500.
<img width="2182" alt="image" src="https://github.com/user-attachments/assets/38dc569b-3b25-45d4-92b4-5b78018427b3">

2. Check the server logs.
```
Traceback (most recent call last):
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/home/seal/anaconda3/envs/test-gpustack/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 162, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/home/seal/anaconda3/envs/test-gpustack/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 29, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/routes/dashboard.py", line 35, in dashboard
    resoruce_counts = await get_resource_counts(session)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/routes/dashboard.py", line 54, in get_resource_counts
    gpu_count += len(worker.status.gpu_devices)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

3. Check the GET worker api response. gpu_devices is null.
<img width="724" alt="image" src="https://github.com/user-attachments/assets/c2416d70-c446-498e-b3af-3d69d91a8f16">

**Expected behavior**

**Environment**

- GPUStack version: v0.1.1
- OS: Ubuntu 22.04.4
- GPU: 

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(f57cb34)
- UI version: ba1670e
- OS: macOS 14.2.1
- GPU: Apple M2, 24G

**Test Result:** pass
