### ISSUE TITLE
Do not run RPC server for iGPU

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#227]
**Describe the bug**

**Steps to reproduce**

1. Install GPUStack. There are an iGPU and an NVIDIA 4090 GPU.

<img width="2287" alt="image" src="https://github.com/user-attachments/assets/741ab3c0-a1a7-4545-93d8-0a5d50cb8382">

2. View the server logs and RPC server logs.

**Result**

1. Failed to run RPC server for GPU 1.
```
2024-09-06T17:12:25+08:00 - gpustack.worker.rpc_server - INFO - Starting llama-box rpc server
2024-09-06T17:12:25+08:00 - gpustack.worker.rpc_server - DEBUG - Run llama-box: /home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/third_party/bin/llama-box/llama-box-linux-amd64-cuda-12.5 rpc server with arguments: --rpc-server-host 0.0.0.0 --rpc-server-port 50991 --rpc-server-main-gpu 1
2024-09-06T17:12:46+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 1 is not running, pid 149723, restarting.
2024-09-06T17:12:46+08:00 - gpustack.worker.worker_manager - ERROR - Failed to terminate process 149723: 'WorkerManager' object has no attribute '_terminate_process_tree'
2024-09-06T17:12:46+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 1 on port 50919, pid 149852
2024-09-06T17:12:46+08:00 - gpustack.worker.rpc_server - INFO - Starting llama-box rpc server
2024-09-06T17:12:46+08:00 - gpustack.worker.rpc_server - DEBUG - Run llama-box: /home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/third_party/bin/llama-box/llama-box-linux-amd64-cuda-12.5 rpc server with arguments: --rpc-server-host 0.0.0.0 --rpc-server-port 50919 --rpc-server-main-gpu 1
2024-09-06T17:13:06+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 1 is not running, pid 149852, restarting.
2024-09-06T17:13:06+08:00 - gpustack.worker.worker_manager - ERROR - Failed to terminate process 149852: 'WorkerManager' object has no attribute '_terminate_process_tree'
2024-09-06T17:13:06+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 1 on port 50477, pid 149926
```

2. Only one device is found. 
```
➜ cat /var/lib/gpustack/log/rpc_server/gpu-1.log
INFO [               rpcserver_start] starting rpc server | hostname="0.0.0.0" port=50898 tid="131825744171008" ts=1725613925
INFO [      rpcserver_create_backend] using CUDA backend | gpu=1 tid="131825744171008" ts=1725613925
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090 D, compute capability 8.9, VMM: yes
ggml_backend_cuda_init: invalid device 1
 ERR [      rpcserver_create_backend] ggml_backend_cuda_init() failed | gpu=1 tid="131825744171008" ts=1725613925
INFO [      rpcserver_create_backend] fallback, using CPU backend | tid="131825744171008" ts=1725613925
CUDA error: invalid device ordinal
  current device: 0, in function ggml_cuda_set_device at /home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cuda.cu:115
  cudaSetDevice(device)
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml-cuda.cu:102: CUDA error
gdb: warning: Couldn't determine a path for the index cache directory.
[New LWP 149636]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000077e509eea42f in __GI___wait4 (pid=149637, stat_loc=0x7fff23c10434, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x000077e509eea42f in __GI___wait4 (pid=149637, stat_loc=0x7fff23c10434, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x000065454a4505a4 in ggml_abort ()
#2  0x000065454a4e0fb6 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) ()
#3  0x000065454a4ef791 in ggml_backend_cuda_get_device_memory ()
#4  0x000065454a252b7d in rpcserver_start(rpcserver_params const&) ()
#5  0x000065454a216e20 in main ()
[Inferior 1 (process 149635) detached]
```

```
➜ nvidia-smi
Fri Sep  6 17:18:53 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0 Off |                  Off |
|  0%   35C    P8              4W /  425W |     617MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1932      G   /usr/lib/xorg/Xorg                            232MiB |
|    0   N/A  N/A      2233      G   /usr/bin/gnome-shell                           14MiB |
|    0   N/A  N/A    137126      C   ...box/llama-box-linux-amd64-cuda-12.5        346MiB |
+-----------------------------------------------------------------------------------------+
```

**Expected behavior**

**Environment**

- GPUStack version: main(654e104)
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4090

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(0e7253a)
- UI version: 5c372bb

**Test Result:** pass
