### ISSUE TITLE
GPUStack upgrade failed 

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#245]
**Describe the bug**

**Steps to reproduce**

1. Install GPUStack v0.1.2 and deploy a model.
2. Upgrade GPUStack.
3. View the GPUStack status.

**Result**

1. Failed to upgarde.
```
2024-09-11T02:12:44+00:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-09-11T02:12:44+00:00 - gpustack.server.server - INFO - Running database migration.
2024-09-11T02:12:44+00:00 - gpustack.cmd.start - CRITICAL - (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL
[SQL: ALTER TABLE models ADD COLUMN placement_strategy VARCHAR(7) NOT NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-09-11T02:12:44+00:00 - gpustack.server.server - INFO - Stopping GPUStack server.
Exception ignored in atexit callback: <bound method Server.at_exit of <gpustack.server.server.Server object at 0x7f912e2ae930>>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/server/server.py", line 193, in at_exit
    process.terminate()
  File "/root/miniconda3/lib/python3.12/multiprocessing/process.py", line 133, in terminate
    self._popen.terminate()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'terminate'
2024-09-11T02:12:45+00:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-09-11T02:12:45+00:00 - gpustack.server.server - INFO - Running database migration.
2024-09-11T02:12:45+00:00 - gpustack.cmd.start - CRITICAL - (sqlite3.OperationalError) duplicate column name: gpu_indexes
[SQL: ALTER TABLE model_instances ADD COLUMN gpu_indexes JSON]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-09-11T02:12:45+00:00 - gpustack.server.server - INFO - Stopping GPUStack server.
Exception ignored in atexit callback: <bound method Server.at_exit of <gpustack.server.server.Server object at 0x7fa33ab37b30>>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/server/server.py", line 193, in at_exit
    process.terminate()
  File "/root/miniconda3/lib/python3.12/multiprocessing/process.py", line 133, in terminate
    self._popen.terminate()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Expected behavior**

**Environment**

- GPUStack version:  main 5d45649
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4080

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main (fa073a7)
- UI version: b6d5b45d
- OS: macOS 14.6.1
- GPU: Apple M2, 24G

**Test Result:** pass
