### ISSUE TITLE
Support downgrade gpustack

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#261]
**Is your enhancement related to a problem? Please describe.**

Now user install the latest version then installing previous versions will result in an error, since previous version doesn't include all the migration script.
```
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
2024-09-12T11:42:12+08:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-09-12T11:42:12+08:00 - gpustack.server.server - INFO - Running database migration.
2024-09-12T11:42:12+08:00 - gpustack.cmd.start - CRITICAL - Can't locate revision identified by '6dcb3a50da19'
2024-09-12T11:42:13+08:00 - gpustack.server.server - INFO - Stopping GPUStack server.
Exception ignored in atexit callback: <bound method Server.at_exit of <gpustack.server.server.Server object at 0x10b12add0>>
Traceback (most recent call last):
  File "/Users/michelia/Documents/project4ai/gpustack/gpustack/server/server.py", line 193, in at_exit
    process.terminate()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/gpustack/lib/python3.11/multiprocessing/process.py", line 133, in terminate
    self._popen.terminate()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Describe the solution you'd like**

Provide an easy way to downgrade

**Comment by wgd2001** [comment]
Is there a solution?

**Comment by wgd2001** [comment]
Is there a solution?

**Comment by gitlawr** [comment]
Currently, the downgrade process for GPUstack requires manual steps.

Below is the detailed workflow when using the installation script on Linux:

1. Install a newer version (e.g., v0.4.0):
```
curl -sfL https://get.gpustack.ai | INSTALL_PACKAGE_SPEC=gpustack==0.4.0 sh -s -
```
2. Backup database migration versions (from `gpustack/migrations/versions` to `db-versions-0_4_0`):
```bash
VENV_PYTHON_PATH=$(pipx environment --value PIPX_LOCAL_VENVS)/gpustack/bin/python
DB_VERSIONS_PATH=$($VENV_PYTHON_PATH -c "import importlib.util; from pathlib import Path; print(Path(importlib.util.find_spec('gpustack').origin).parent)")/migrations/versions
cp -r $DB_VERSIONS_PATH ./db_versions_0_4_0
```
3. Install a previous version (e.g., v0.3.2):
```
curl -sfL https://get.gpustack.ai | INSTALL_PACKAGE_SPEC=gpustack==0.3.2 sh -s -
```
4. Restore database migration versions:
```
cp db_versions_0_4_0/* $DB_VERSIONS_PATH
```

5. Verify GPUstack status.
