### ISSUE TITLE
Optimize logs printing when getting logs fails

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#275]
**Is your enhancement related to a problem? Please describe.**

When the GPUStack server cannot access the worker,  the GET `/v1/model-instances/{id}/logs` api will report an error.

<img width="575" alt="image" src="https://github.com/user-attachments/assets/92520bb5-6d4b-4105-9c39-2b920b35b263">

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/sophia/miniconda3/envs/gpustack/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/sophia/miniconda3/envs/gpustack/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/gpustack/gpustack/api/middlewares.py", line 162, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/sophia/miniconda3/envs/gpustack/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/gpustack/gpustack/api/middlewares.py", line 29, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/gpustack/gpustack/routes/model_instances.py", line 107, in get_serving_logs
    response = await client.get(model_instance_log_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/Users/sophia/miniconda3/envs/gpustack/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sophia/Library/Caches/pypoetry/virtualenvs/gpustack-AgeWfJ-k-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Finenyaco** [comment]
Verified on main db35f98

<img width="1222" alt="Image" src="https://github.com/user-attachments/assets/b2f80d06-b403-46a6-b74b-f0d019039e62" />
