### ISSUE TITLE
Failed to deploy model instance after setting the llama-box parameters

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#328]
**Describe the bug**

**Steps to reproduce**

1. Deploy a model from ollama.
2. Set the `--parallel` to 2 as shown below:
<img width="564" alt="image" src="https://github.com/user-attachments/assets/165fa672-54d1-4578-b22f-d463110461b2">

3. View the instance status and logs

**Result**

1.  Failed to deploy.

<img width="2508" alt="image" src="https://github.com/user-attachments/assets/4fa91540-c6ec-4ea3-b600-78f63b47a9c1">

**Expected behavior**

**Environment**

- GPUStack version: main e6f4604ee297fde4d750efefc65ee1e9bfe607c2
- OS: macOS 14.6.1
- GPU: Apple M2

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(74d5e7c)
- OS: macOS 14.6.1
- GPU: Apple M2, 24G

**Test Result:** pass

**Comment by Finenyaco** [comment]
Failed to deploy instance using llama-box when setting the `--no-warmup` parameter.
```
2024-09-30T17:29:07+08:00 - gpustack.worker.serve_manager - INFO - Start serving model instance gemma-2-27b-it-qPXog on port 40494
Process Process-5:
Traceback (most recent call last):
  File "/Users/seal/miniconda3/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/seal/miniconda3/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/worker/serve_manager.py", line 163, in serve_model_instance
    LlamaBoxServer(clientset, mi, cfg).start()
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/worker/backends/llama_box.py", line 88, in start
    key, value = param.split('=', 1)
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(b64ffc1)
- UI version: 5c2503b
- OS: macOS 14.6.1
- GPU: Apple M2, 24G

**Test Result:** pass
