### ISSUE TITLE
Some models should be run without using the trust_remote_code argument in vllm

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#340]
**Describe the bug**

**Steps to reproduce**

1. Deploy a model `tiiuae/falcon-7b-instruct` from Hugging Face.
2. View the instance logs.

**Result**

1. Failed to deploy. Cannot run model with  trust_remote_code=True argument.
```
WARNING: You are currently loading Falcon using legacy code contained in the model repository. Falcon has now been fully ported into the Hugging Face transformers library. For the most up-to-date and high-performance version of the Falcon model code, please update to the latest version of transformers and then load the model without the trust_remote_code=True argument.

WARNING 09-29 17:34:33 config.py:1715] The model's config.json does not contain any of the following keys to determine the original maximum length of the model: ['max_position_embeddings', 'n_positions', 'max_seq_len', 'seq_length', 'model_max_length', 'max_sequence_length', 'max_seq_length', 'seq_len']. Assuming the model's maximum length is 2048.
/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884 
  warnings.warn(

WARNING: You are currently loading Falcon using legacy code contained in the model repository. Falcon has now been fully ported into the Hugging Face transformers library. For the most up-to-date and high-performance version of the Falcon model code, please update to the latest version of transformers and then load the model without the trust_remote_code=True argument.

WARNING 09-29 17:34:34 config.py:1715] The model's config.json does not contain any of the following keys to determine the original maximum length of the model: ['max_position_embeddings', 'n_positions', 'max_seq_len', 'seq_length', 'model_max_length', 'max_sequence_length', 'max_seq_length', 'seq_len']. Assuming the model's maximum length is 2048.
INFO 09-29 17:34:34 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='/var/lib/gpustack/cache/huggingface/models--tiiuae--falcon-7b-instruct/snapshots/b22819d8a855bb887bdbdf45d6a94f815d3a195e', speculative_config=None, tokenizer='/var/lib/gpustack/cache/huggingface/models--tiiuae--falcon-7b-instruct/snapshots/b22819d8a855bb887bdbdf45d6a94f815d3a195e', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=falcon-7b-instruct, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=True, mm_processor_kwargs=None)
/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884 
  warnings.warn(
INFO 09-29 17:34:35 model_runner.py:1014] Starting to load model /var/lib/gpustack/cache/huggingface/models--tiiuae--falcon-7b-instruct/snapshots/b22819d8a855bb887bdbdf45d6a94f815d3a195e...
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/seal/anaconda3/envs/test-gpustack/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/seal/anaconda3/envs/test-gpustack/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 388, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 138, in from_engine_args
    return cls(
           ^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 78, in __init__
    self.engine = LLMEngine(*args,
                  ^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 325, in __init__
    self.model_executor = executor_class(
                          ^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 47, in __init__
    self._init_executor()
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
    self.driver_worker.load_model()
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/worker/worker.py", line 183, in load_model
    self.model_runner.load_model()
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1016, in load_model
    self.model = get_model(model_config=self.model_config,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
    return loader.load_model(model_config=model_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 399, in load_model
    model = _initialize_model(model_config, self.load_config,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 176, in _initialize_model
    return build_model(
           ^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 161, in build_model
    return model_class(config=hf_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/falcon.py", line 389, in __init__
    self.transformer = FalconModel(config, cache_config, quant_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/falcon.py", line 351, in __init__
    FalconDecoderLayer(config, cache_config, quant_config)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/falcon.py", line 249, in __init__
    if (config.num_ln_in_parallel_attn is None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/transformers/configuration_utils.py", line 202, in __getattribute__
    return super().__getattribute__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FalconConfig' object has no attribute 'num_ln_in_parallel_attn'
Traceback (most recent call last):
  File "/home/seal/.local/share/pipx/venvs/gpustack/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/scripts.py", line 165, in main
    args.dispatch_function(args)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/scripts.py", line 37, in serve
    uvloop.run(run_server(args))
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/home/seal/anaconda3/envs/test-gpustack/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/seal/anaconda3/envs/test-gpustack/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 538, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/home/seal/anaconda3/envs/test-gpustack/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 105, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/home/seal/anaconda3/envs/test-gpustack/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 192, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start
```

**Expected behavior**

**Environment**

- GPUStack version: main 447ac69
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4090

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(9621cd3)

**Test Result:**

Now the default is not to use the `--trust-remote-code` parameter. If necessary, it can be manually added.

<img width="565" alt="image" src="https://github.com/user-attachments/assets/cc967131-2f34-45f1-975c-eeb3960f0992">
