### ISSUE TITLE
Model instance OOM due to large context length in OpenGVLab/internvl2-4b model

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#364]
**Describe the bug**

**Steps to reproduce**

1. Deploy a model 'OpenGVLab/InternVL2-4B' from Hugging Face and configure the backend. parameter `--trust-remote-code`.
2. View the instance logs.

**Result**

```
Fetching 22 files: 100%|██████████| 22/22 [00:00<00:00, 90732.24it/s]
INFO 10-08 10:51:58 api_server.py:526] vLLM API server version 0.6.1.dev238+ge2c6e0a82
INFO 10-08 10:51:58 api_server.py:527] args: Namespace(model_tag='/var/lib/gpustack/cache/huggingface/models--OpenGVLab--InternVL2-4B/snapshots/50b4a2c17e5b7344e074a9f8df8932b68eaa8891', config='', host='0.0.0.0', port=40057, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, model='/var/lib/gpustack/cache/huggingface/models--OpenGVLab--InternVL2-4B/snapshots/50b4a2c17e5b7344e074a9f8df8932b68eaa8891', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', config_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=False, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['internvl2-4b'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, override_neuron_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, dispatch_function=<function serve at 0x71e73905dbc0>)
INFO 10-08 10:51:58 api_server.py:164] Multiprocessing frontend to use ipc:///tmp/d708ae08-c089-4d16-875e-3083d04c1e0a for IPC Path.
INFO 10-08 10:51:58 api_server.py:177] Started engine process with PID 16183
WARNING 10-08 10:51:58 arg_utils.py:940] The model has a long context length (131072). This may cause OOM errors during the initial memory profiling phase, or result in low performance due to small KV cache space. Consider setting --max-model-len to a smaller value.
WARNING 10-08 10:51:59 arg_utils.py:940] The model has a long context length (131072). This may cause OOM errors during the initial memory profiling phase, or result in low performance due to small KV cache space. Consider setting --max-model-len to a smaller value.
INFO 10-08 10:51:59 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='/var/lib/gpustack/cache/huggingface/models--OpenGVLab--InternVL2-4B/snapshots/50b4a2c17e5b7344e074a9f8df8932b68eaa8891', speculative_config=None, tokenizer='/var/lib/gpustack/cache/huggingface/models--OpenGVLab--InternVL2-4B/snapshots/50b4a2c17e5b7344e074a9f8df8932b68eaa8891', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=internvl2-4b, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=True, mm_processor_kwargs=None)
INFO 10-08 10:52:00 selector.py:240] Cannot use FlashAttention-2 backend due to sliding window.
INFO 10-08 10:52:00 selector.py:116] Using XFormers backend.
/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
INFO 10-08 10:52:00 model_runner.py:1014] Starting to load model /var/lib/gpustack/cache/huggingface/models--OpenGVLab--InternVL2-4B/snapshots/50b4a2c17e5b7344e074a9f8df8932b68eaa8891...
INFO 10-08 10:52:00 selector.py:240] Cannot use FlashAttention-2 backend due to sliding window.
INFO 10-08 10:52:00 selector.py:116] Using XFormers backend.
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00, 401.18it/s]

INFO 10-08 10:52:01 model_runner.py:1025] Loading model weights took 7.7740 GB
INFO 10-08 10:52:02 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241008-105202.pkl...
INFO 10-08 10:52:03 model_runner_base.py:149] Completed writing input of failed execution to /tmp/err_execute_model_input_20241008-105202.pkl.
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1590, in execute_model
    hidden_or_intermediate_states = model_executable(
                                    ^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/internvl.py", line 495, in forward
    vision_embeddings = self._process_image_input(image_input)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/internvl.py", line 478, in _process_image_input
    image_embeds = self.extract_feature(image_input["data"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/internvl.py", line 402, in extract_feature
    vit_embeds = self.vision_model(pixel_values=pixel_values)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/intern_vit.py", line 356, in forward
    encoder_outputs = self.encoder(inputs_embeds=hidden_states)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/intern_vit.py", line 298, in forward
    hidden_states = encoder_layer(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/intern_vit.py", line 267, in forward
    hidden_states = hidden_states + self.attn(
                                    ^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/models/intern_vit.py", line 134, in forward
    qkv, _ = self.qkv(x)
             ^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 367, in forward
    output_parallel = self.quant_method.apply(self, input_, bias)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 135, in apply
    return F.linear(x, layer.weight, bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.97 GiB. GPU 0 has a total capacity of 15.61 GiB of which 2.82 GiB is free. Process 3922 has 246.00 MiB memory in use. Including non-PyTorch memory, this process has 12.52 GiB memory in use. Of the allocated memory 11.65 GiB is allocated by PyTorch, and 605.89 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sophia/miniconda3/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/sophia/miniconda3/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 388, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 138, in from_engine_args
    return cls(
           ^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 78, in __init__
    self.engine = LLMEngine(*args,
                  ^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 339, in __init__
    self._initialize_kv_caches()
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 474, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/executor/gpu_executor.py", line 114, in determine_num_available_blocks
    return self.driver_worker.determine_num_available_blocks()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/worker/worker.py", line 223, in determine_num_available_blocks
    self.model_runner.profile_run()
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1236, in profile_run
    self.execute_model(model_input, kv_caches, intermediate_tensors)
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/worker/model_runner_base.py", line 152, in _wrapper
    raise type(err)(
torch.OutOfMemoryError: Error in model execution (input dumped to /tmp/err_execute_model_input_20241008-105202.pkl): CUDA out of memory. Tried to allocate 2.97 GiB. GPU 0 has a total capacity of 15.61 GiB of which 2.82 GiB is free. Process 3922 has 246.00 MiB memory in use. Including non-PyTorch memory, this process has 12.52 GiB memory in use. Of the allocated memory 11.65 GiB is allocated by PyTorch, and 605.89 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/sophia/.local/share/pipx/venvs/gpustack/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/scripts.py", line 165, in main
    args.dispatch_function(args)
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/scripts.py", line 37, in serve
    uvloop.run(run_server(args))
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/home/sophia/miniconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/sophia/miniconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 538, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/home/sophia/miniconda3/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 105, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/home/sophia/miniconda3/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 192, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start
```

**Expected behavior**

When the default context length exceeds 8192,  --max-model-len=8192 should be set. https://github.com/gpustack/gpustack/issues/313

**Environment**

- GPUStack version: v0.3.0

**Additional context**

**Comment by gitlawr** [comment]
It uses a custom [Config](https://huggingface.co/OpenGVLab/InternVL2-4B/blob/main/config.json#L7) that contains no max context length info. In this case, users need to specify `--max-model-len` to override the default.

**Comment by Finenyaco** [comment]
Verified on main.

Configure `--max-model-len` manually.

<img width="2096" alt="image" src="https://github.com/user-attachments/assets/5a2a9e13-02de-4ecb-81bd-31eef12758be">
