### ISSUE TITLE
CPU overload occurs due to insufficient memory when running models with vllm

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#375]
**Describe the bug**

When deploying models with VLLM and encountering insufficient memory, the system is unable to recover automatically.

**Steps to reproduce**

1. Deploy Qwen/Qwen2.5-0.5B-Instruct using the vllm inference engine.

<img width="1445" alt="image" src="https://github.com/user-attachments/assets/dd419c87-952f-42f1-a0eb-7f9359a7ce21">

2. Go to the playground and  chat using the model in step 1.

**Result**

The CPU is constantly overloaded, and a system reboot is required to recover.

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/fae75139-51b5-4393-a44e-d8f23a84faed">

**Expected behavior**

**Environment**

- GPUStack version: 0.3.0
- OS: openEuler 20.03 (LTS-SP3), 4C8G
- GPU: NVIDIA GeForce RTX 4080 SUPER

**Additional context**

- If run the same model using vllm manually,  the CPU usage will decrease.

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/ab636b2f-5b3f-48a7-b994-db1ba2b01104">

```
INFO:     Uvicorn running on http://0.0.0.0:40666 (Press CTRL+C to quit)
INFO 10-11 17:22:27 metrics.py:351] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 10-11 17:22:37 metrics.py:351] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 10-11 17:22:47 logger.py:36] Received request chat-206afc4fd6494a08939bea5bf09c4542: prompt: '<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\n', params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1024, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: [151644, 8948, 198, 2610, 525, 1207, 16948, 11, 3465, 553, 54364, 14817, 13, 1446, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 6023, 151645, 198, 151644, 77091, 198], lora_request: None, prompt_adapter_request: None.
INFO 10-11 17:22:47 engine.py:288] Added request chat-206afc4fd6494a08939bea5bf09c4542.
ERROR 10-11 17:23:09 client.py:244] RuntimeError('Engine loop has died')
ERROR 10-11 17:23:09 client.py:244] Traceback (most recent call last):
ERROR 10-11 17:23:09 client.py:244]   File "/root/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/multiprocessing/client.py", line 144, in run_heartbeat_loop
ERROR 10-11 17:23:09 client.py:244]     await self._check_success(
ERROR 10-11 17:23:09 client.py:244]   File "/root/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/vllm/engine/multiprocessing/client.py", line 308, in _check_success
ERROR 10-11 17:23:09 client.py:244]     raise response
ERROR 10-11 17:23:09 client.py:244] RuntimeError: Engine loop has died
CRITICAL 10-11 17:23:17 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:40220 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2285]
(base) [root@localhost ~]# /root/miniconda3/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

- After upgrading the memory to 12GB, the model runs normally through GPUStack.

**Comment by gitlawr** [comment]
No longer relevant in the latest version.
