### ISSUE TITLE
Failed to upgrade the server: Cannot add a NOT NULL column with default value NULL

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#379]
**Describe the bug**

**Steps to reproduce**

1. Install GPUStack 0.3.0
2. Upgrade to main.

**Result**

1.  Failed to upgrade.
```
2024-10-12T14:33:53+08:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-10-12T14:33:53+08:00 - gpustack.server.server - INFO - Running database migration.
2024-10-12T14:33:53+08:00 - gpustack.cmd.start - CRITICAL - (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL
[SQL: ALTER TABLE models ADD COLUMN reranker BOOLEAN NOT NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-10-12T14:33:53+08:00 - gpustack.server.server - INFO - Stopping GPUStack server.
Exception ignored in atexit callback: <bound method Server.at_exit of <gpustack.server.server.Server object at 0x111512e40>>
Traceback (most recent call last):
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/server/server.py", line 193, in at_exit
    process.terminate()
  File "/Users/sophia/miniconda3/envs/gpustack-test/lib/python3.12/multiprocessing/process.py", line 133, in terminate
    self._popen.terminate()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'terminate'
2024-10-12T14:33:57+08:00 - gpustack.worker.serve_manager - DEBUG - Started watching model instances.
2024-10-12T14:34:02+08:00 - gpustack.worker.serve_manager - DEBUG - Started watching model instances.
```

**Expected behavior**

**Environment**

- GPUStack version: main

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(eb3baf9)

**Test Result:** pass
