### ISSUE TITLE
The third-party tools failed to download and did not automatically retry

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#397]
**Describe the bug**

**Steps to reproduce**

1. Install GPUStack:
```
curl -sfL https://raw.githubusercontent.com/gpustack/gpustack/main/install.sh |  INSTALL_PACKAGE_SPEC=/home/ubuntu/gpustack-0.0.0-py3-none-manylinux2014_x86_64.whl[vllm] sh -s - -d
```

**Result**

Failed to download fastfetch-linux-amd64 '2.25.0.1' but it didn't automatically retry. Restart the service is required.
```
2024-10-15T17:11:17+08:00 - gpustack.server.server - DEBUG - System load collector started.
2024-10-15T17:11:17+08:00 - gpustack.server.server - DEBUG - Worker syncer started.
2024-10-15T17:11:17+08:00 - gpustack.server.server - INFO - Serving on 0.0.0.0:80.
2024-10-15T17:11:17+08:00 - gpustack.scheduler.scheduler - INFO - Scheduler started.
2024-10-15T17:11:17+08:00 - gpustack.worker.tools_manager - DEBUG - Using https://github.com as the base URL for downloading dependency tools
2024-10-15T17:11:17+08:00 - gpustack.worker.tools_manager - DEBUG - Preparing dependency tools
2024-10-15T17:11:17+08:00 - gpustack.worker.tools_manager - DEBUG - OS: linux, Arch: amd64, Device:
2024-10-15T17:11:17+08:00 - gpustack.worker.tools_manager - INFO - downloading llama-box-linux-amd64-avx2 'v0.0.59-sp2'
2024-10-15T17:12:55+08:00 - gpustack.worker.tools_manager - INFO - downloading gguf-parser-linux-amd64 'v0.11.1'
2024-10-15T17:14:24+08:00 - gpustack.worker.tools_manager - INFO - downloading fastfetch-linux-amd64 '2.25.0.1'
Process Process-1:
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:983: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/worker/tools_manager.py", line 240, in _download_file
    with requests.get(url, stream=True, timeout=30) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/worker/worker.py", line 111, in start
    tools_manager.prepare_tools()
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/worker/tools_manager.py", line 64, in prepare_tools
    self.download_fastfetch()
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/worker/tools_manager.py", line 195, in download_fastfetch
    self._download_file(url, tmp_file)
  File "/home/ubuntu/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/worker/tools_manager.py", line 245, in _download_file
    raise Exception(f"error downloading from {url}: {e}")
Exception: error downloading from https://github.com/gpustack/fastfetch/releases/download/2.25.0.1/fastfetch-linux-amd64.zip: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=30)
```

**Expected behavior**

**Environment**

- GPUStack version: main 04f4602
- OS: Ubuntu 24.04

**Additional context**

After restarting the GPUStack service.
```
2024-10-15T17:40:31+08:00 - gpustack.server.server - INFO - Stopping GPUStack server.
2024-10-15T17:40:31+08:00 - gpustack.server.server - INFO - Stopped all processes.
2024-10-15T17:40:33+08:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-10-15T17:40:33+08:00 - gpustack.server.server - INFO - Running database migration.
2024-10-15T17:40:33+08:00 - gpustack.server.server - INFO - Database migration completed.
2024-10-15T17:40:34+08:00 - gpustack.server.server - DEBUG - Data initialization completed.
2024-10-15T17:40:34+08:00 - gpustack.server.server - DEBUG - Scheduler started.
2024-10-15T17:40:34+08:00 - gpustack.server.server - DEBUG - Controllers started.
2024-10-15T17:40:34+08:00 - gpustack.server.server - DEBUG - System load collector started.
2024-10-15T17:40:34+08:00 - gpustack.server.server - DEBUG - Worker syncer started.
2024-10-15T17:40:34+08:00 - gpustack.server.server - INFO - Serving on 0.0.0.0:80.
2024-10-15T17:40:34+08:00 - gpustack.scheduler.scheduler - INFO - Scheduler started.
2024-10-15T17:40:37+08:00 - gpustack.worker.tools_manager - DEBUG - Failed to connect to https://github.com: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x72a2f1b42270>, 'Connection to github.com timed out. (connect timeout=3)'))
2024-10-15T17:40:37+08:00 - gpustack.worker.tools_manager - DEBUG - Using https://gpustack-1303613262.cos.ap-guangzhou.myqcloud.com as the base URL for downloading dependency tools
2024-10-15T17:40:37+08:00 - gpustack.worker.tools_manager - DEBUG - Preparing dependency tools
2024-10-15T17:40:37+08:00 - gpustack.worker.tools_manager - DEBUG - OS: linux, Arch: amd64, Device:
2024-10-15T17:40:37+08:00 - gpustack.worker.tools_manager - DEBUG - llama-box already exists, skipping download
2024-10-15T17:40:37+08:00 - gpustack.worker.tools_manager - DEBUG - gguf-parser already exists, skipping download
2024-10-15T17:40:37+08:00 - gpustack.worker.tools_manager - INFO - downloading fastfetch-linux-amd64 '2.25.0.1'
2024-10-15T17:40:37+08:00 - gpustack.worker.worker - INFO - Starting GPUStack worker.
2024-10-15T17:40:37+08:00 - gpustack.worker.worker - INFO - Serving worker APIs on 0.0.0.0:10150.
2024-10-15T17:40:37+08:00 - gpustack.worker.exporter - INFO - Serving metric exporter on 0.0.0.0:10151.
2024-10-15T17:40:37+08:00 - gpustack.worker.worker_manager - INFO - Registering worker: VM-3-13-ubuntu
2024-10-15T17:40:37+08:00 - gpustack.worker.worker_manager - INFO - Worker VM-3-13-ubuntu registered.
2024-10-15T17:40:40+08:00 - gpustack.worker.serve_manager - DEBUG - Started watching model instances.
```

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(5c6ef4e)
- OS: Ubuntu 24.04

**Test Result:** pass
```
2024-10-18T15:36:16+08:00 - gpustack.server.server - DEBUG - Controllers started.
2024-10-18T15:36:16+08:00 - gpustack.server.server - DEBUG - System load collector started.
2024-10-18T15:36:16+08:00 - gpustack.server.server - DEBUG - Worker syncer started.
2024-10-18T15:36:16+08:00 - gpustack.server.server - DEBUG - Update checker started.
2024-10-18T15:36:16+08:00 - gpustack.server.server - INFO - Serving on 0.0.0.0:80.
2024-10-18T15:36:16+08:00 - gpustack.scheduler.scheduler - INFO - Scheduler started.
2024-10-18T15:36:16+08:00 - gpustack.worker.tools_manager - DEBUG - Using https://github.com as the base URL for downloading dependency tools
2024-10-18T15:36:16+08:00 - gpustack.worker.tools_manager - DEBUG - Preparing dependency tools
2024-10-18T15:36:16+08:00 - gpustack.worker.tools_manager - DEBUG - OS: linux, Arch: amd64, Device:
2024-10-18T15:36:16+08:00 - gpustack.worker.tools_manager - INFO - downloading llama-box-linux-amd64-avx2 'v0.0.65'
2024-10-18T15:40:28+08:00 - gpustack.worker.tools_manager - INFO - downloading gguf-parser-linux-amd64 'v0.11.1'
2024-10-18T15:51:52+08:00 - gpustack.worker.tools_manager - INFO - downloading fastfetch-linux-amd64 '2.25.0.1'
2024-10-18T15:52:02+08:00 - gpustack.worker.tools_manager - DEBUG - Attempt 1 failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying in 2 seconds...
2024-10-18T15:53:35+08:00 - gpustack.worker.worker - INFO - Starting GPUStack worker.
2024-10-18T15:53:35+08:00 - gpustack.worker.worker - INFO - Serving worker APIs on 0.0.0.0:10150.
2024-10-18T15:53:35+08:00 - gpustack.worker.exporter - INFO - Serving metric exporter on 0.0.0.0:10151.
2024-10-18T15:53:35+08:00 - gpustack.worker.worker_manager - INFO - Registering worker: VM-16-13-ubuntu
2024-10-18T15:53:35+08:00 - gpustack.worker.worker_manager - INFO - Worker VM-16-13-ubuntu registered.
2024-10-18T15:53:38+08:00 - gpustack.worker.serve_manager - DEBUG - Started watching model instances.
```
