### ISSUE TITLE
Failed to add rerank model in dify - TypeError: string indices must be integers

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#456]
**Describe the bug**

```
2024-10-24 09:42:47,383.383 INFO [Dummy-3] [_client.py:1038] - HTTP Request: POST http://192.168.50.4/v1/rerank "HTTP/1.1 200 OK"
2024-10-24 09:42:47,384.384 ERROR [Dummy-3] [models.py:160] - save model credentials error: string indices must be integers
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/jina/rerank/rerank.py", line 93, in validate_credentials
    self._invoke(
  File "/app/api/core/model_runtime/model_providers/jina/rerank/rerank.py", line 66, in _invoke
    text = result["document"]["text"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/controllers/console/workspace/models.py", line 152, in post
    model_provider_service.save_model_credentials(
  File "/app/api/services/model_provider_service.py", line 250, in save_model_credentials
    provider_configuration.add_or_update_custom_model_credentials(
  File "/app/api/core/entities/provider_configuration.py", line 390, in add_or_update_custom_model_credentials
    provider_model_record, credentials = self.custom_model_credentials_validate(model_type, model, credentials)
  File "/app/api/core/entities/provider_configuration.py", line 370, in custom_model_credentials_validate
    credentials = model_provider_factory.model_credentials_validate(
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 123, in model_credentials_validate
    model_instance.validate_credentials(model, filtered_credentials)
  File "/app/api/core/model_runtime/model_providers/jina/rerank/rerank.py", line 106, in validate_credentials
    raise CredentialsValidateFailedError(str(ex))
core.model_runtime.errors.validate.CredentialsValidateFailedError: string indices must be integers
```

**Steps to reproduce**

1. Deploy bge-reranker-v2-m3 model in GPUStack;
2. Deploy Dify:
```
git clone -b 0.10.1 https://github.com/langgenius/dify.git
cd dify/docker/
cp .env.example .env
docker compose up -d
```
3. Log in and add Jina type rerank model in Dify.

**Result**

It reports error:
```
string indices must be integers
```

Error code:
```
for result in results["results"]:
    rerank_document = RerankDocument(
        index=result["index"],
        text=result["document"]["text"],
        score=result["relevance_score"],
    )
```

Workaround code:
```
for result in results["results"]:
    print(result)  
    print(type(result["document"]))

    if isinstance(result["document"], dict):
        rerank_document = RerankDocument(
            index=result["index"],
            text=result["document"]["text"],
            score=result["relevance_score"],
        )
    else:
        rerank_document = RerankDocument(
            index=result["index"],
            text=result["document"],
            score=result["relevance_score"],
        )
```

**Environment**

- GPUStack version: b60b91e
- OS: macOS
- GPU: M2 Ultra

**Comment by Finenyaco** [comment]
Verified on 0.3.1rc1, llama-box version v0.0.70
