### ISSUE TITLE
failed to collect system load: 'validated_data' must be provided if 'call_default_factory' is True

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#581]
**Describe the bug**

**Steps to reproduce**

1. Install GPUStack
2. Go to the dashboard

**Result**

There was an error.
<img width="2306" alt="image" src="https://github.com/user-attachments/assets/ba01c8d0-ad9b-4d28-a5b5-0973f6834669">

```
2024-11-21T10:23:18+08:00 - gpustack.server.system_load - ERROR - failed to collect system load: 'validated_data' must be provided if 'call_default_factory' is True.
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/Users/seal/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 235, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/Users/seal/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 38, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/Users/seal/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 32, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/routes/dashboard.py", line 37, in dashboard
    |     system_load = await get_system_load(session)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/routes/dashboard.py", line 68, in get_system_load
    |     current_system_load = compute_system_load(workers)
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/server/system_load.py", line 65, in compute_system_load
    |     load = SystemLoad()
    |            ^^^^^^^^^^^^
    |   File "<string>", line 4, in __init__
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 571, in _initialize_instance
    |     with util.safe_reraise():
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    |     raise exc_value.with_traceback(exc_tb)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 569, in _initialize_instance
    |     manager.original_init(*mixed[1:], **kwargs)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlmodel/main.py", line 723, in __init__
    |     sqlmodel_init(self=__pydantic_self__, data=data)
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlmodel/_compat.py", line 348, in sqlmodel_init
    |     sqlmodel_table_construct(
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlmodel/_compat.py", line 248, in sqlmodel_table_construct
    |     defaults[name] = field.get_default(call_default_factory=True)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/pydantic/fields.py", line 596, in get_default
    |     raise ValueError("'validated_data' must be provided if 'call_default_factory' is True.")
    | ValueError: 'validated_data' must be provided if 'call_default_factory' is True.
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/Users/seal/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 235, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/Users/seal/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 38, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/Users/seal/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 32, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/routes/dashboard.py", line 37, in dashboard
    system_load = await get_system_load(session)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/routes/dashboard.py", line 68, in get_system_load
    current_system_load = compute_system_load(workers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/server/system_load.py", line 65, in compute_system_load
    load = SystemLoad()
           ^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 571, in _initialize_instance
    with util.safe_reraise():
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlmodel/main.py", line 723, in __init__
    sqlmodel_init(self=__pydantic_self__, data=data)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlmodel/_compat.py", line 348, in sqlmodel_init
    sqlmodel_table_construct(
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlmodel/_compat.py", line 248, in sqlmodel_table_construct
    defaults[name] = field.get_default(call_default_factory=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/pydantic/fields.py", line 596, in get_default
    raise ValueError("'validated_data' must be provided if 'call_default_factory' is True.")
ValueError: 'validated_data' must be provided if 'call_default_factory' is True.
2024-11-21T10:24:18+08:00 - gpustack.server.system_load - ERROR - failed to collect system load: 'validated_data' must be provided if 'call_default_factory' is True.
```

**Expected behavior**

**Environment**

- GPUStack version: main 63c9248

**Additional context**

**Comment by gitlawr** [comment]
There's probably incompatible changes in the new release of pydantic: https://pypi.org/project/pydantic/2.10.0/. The workaround is to downgrade pydantic to 2.9.2. e.g., 
```bash
pipx runpip gpustack install pydantic==2.9.2
systemctl restart gpustack
```

**Comment by gitlawr** [comment]
Reproducible in a fresh 0.3.2 setup

**Comment by Finenyaco** [comment]
**Test Result:**
- 0.3.2: pass
- main 926f2ee: pass
