### ISSUE TITLE
Image generation crashes for certain sizes

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#661]
**Steps to reproduce**

1. Deploy model `Hugging Face/gpustack/stable-diffusion-xl-base-1.0-GGUF`.
2. Generate an image with custom size 800x1200

**Result**

1. Failed to generate the image. 
<img width="1933" alt="image" src="https://github.com/user-attachments/assets/98c23511-e42d-4e50-8aa1-7cceda35555e">

2. Instance crashed.
```
/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.10/site-packages/gpustack/third_party/bin/llama-box/llama-box --host 0.0.0.0 --embeddings --gpu-layers -1 --parallel 4 --ctx-size 8192 --port 40178 --model /opt/models/huggingface/models--gpustack--stable-diffusion-xl-base-1.0-GGUF/snapshots/f00927e80a399ecb0bcacca868131d5e9d4e77aa/./stable-diffusion-xl-base-1.0-Q8_0.gguf --no-mmap --images --image-schedule karras --log-verbosity 3 --image-no-text-encoder-model-offload
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml.c:2341: GGML_ASSERT(a->ne[d] == b->ne[d]) failed
gdb: warning: Couldn't determine a path for the index cache directory.
[New LWP 323983]
[New LWP 323984]
[New LWP 323985]
[New LWP 323986]
[New LWP 323987]
[New LWP 323988]
[New LWP 323989]
[New LWP 323990]
[New LWP 323991]
[New LWP 323992]
[New LWP 323993]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000072a0c9eea42f in __GI___wait4 (pid=324232, stat_loc=0x7ffd887e29a4, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x000072a0c9eea42f in __GI___wait4 (pid=324232, stat_loc=0x7ffd887e29a4, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x00000000009adf2a in ggml_abort ()
#2  0x00000000009b4420 in ggml_concat ()
#3  0x000000000063deba in UnetModelBlock::forward(ggml_context*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, int, std::vector<ggml_tensor*, std::allocator<ggml_tensor*> >, float) ()
#4  0x000000000063fed4 in std::_Function_handler<ggml_cgraph* (), UNetModelRunner::compute(int, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, int, std::vector<ggml_tensor*, std::allocator<ggml_tensor*> >, float, ggml_tensor**, ggml_context*)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#5  0x00000000005d402c in GGMLRunner::compute(std::function<ggml_cgraph* ()>, int, bool, ggml_tensor**, ggml_context*) ()
#6  0x00000000005d4b10 in UNetModel::compute(int, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, int, std::vector<ggml_tensor*, std::allocator<ggml_tensor*> >, float, ggml_tensor**, ggml_context*, std::vector<int, std::allocator<int> >) ()
#7  0x00000000005bc32b in sd_sampling_stream_sample::{lambda(ggml_tensor*, float, int)#1}::operator()(ggml_tensor*, float, int) const ()
#8  0x00000000005d8cb6 in EULERASampler::sample(std::function<ggml_tensor* (ggml_tensor*, float, int)>, ggml_context*, ggml_tensor*, std::vector<float, std::allocator<float> >, std::shared_ptr<RNG>, int) ()
#9  0x00000000005bba55 in sd_sampling_stream_sample ()
#10 0x000000000050d8b0 in server_context::update_slots() ()
#11 0x000000000051a23a in server_queue::start_loop() ()
#12 0x0000000000433079 in main ()
[Inferior 1 (process 323980) detached]

```

**Environment**

- GPUStack version: main
- OS: Ubuntu 22.04
- GPU: NVIDIA 4090

**Additional context**

**Comment by gitlawr** [comment]
No longer relevant in the latest version.
