### ISSUE TITLE
instance stuck in scheduled state after recreation on Windows

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#682]
**Describe the bug**

<img width="1281" alt="image" src="https://github.com/user-attachments/assets/864a420e-b3f3-4712-9281-66ca3318a473">
**Steps to reproduce**

1. Install main
2. Deploy qwen2.5:0.5b ollama model
3. After the instance turns to running, delete the instance to recreate another.

**Result**

The instance is in `Scheduled` state.

**Environment**

- GPUStack version: main
- OS: windows arm64
- GPU: None

**Additional context**
server logs:
```
2024-12-02T17:37:20+08:00 - gpustack.scheduler.calculator - INFO - Calculated resource claim for full offload model instance qw-5XisF, claim: memoryEstimate(fullOffloaded=True, ram=layerMemoryEstimate(uma=238172440, nonuma=395458840, handleLayers=0), vrams=[layerMemoryEstimate(uma=493134336, nonuma=1085059584, handleLayers=24)], offloadLayers=25)
2024-12-02T17:37:45+08:00 - sqlalchemy.pool.impl.NullPool - ERROR - Exception closing connection <AdaptedConnection <Connection(Thread-223, started daemon 3808)>>
Traceback (most recent call last):
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\pool\base.py", line 376, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\engine\default.py", line 708, in do_close
    dbapi_connection.close()
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 275, in close
    self.await_(self._connection.close())
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\aiosqlite\core.py", line 178, in close
    await self._execute(self._conn.close)
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\aiosqlite\core.py", line 132, in _execute
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1ea46b9c1a0
2024-12-02T17:38:10+08:00 - sqlalchemy.pool.impl.NullPool - ERROR - Exception closing connection <AdaptedConnection <Connection(Thread-228, started daemon 36952)>>
Traceback (most recent call last):
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\pool\base.py", line 376, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\engine\default.py", line 708, in do_close
    dbapi_connection.close()
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 275, in close
    self.await_(self._connection.close())
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\aiosqlite\core.py", line 178, in close
    await self._execute(self._conn.close)
  File "C:\Users\seal\pipx\venvs\gpustack\Lib\site-packages\aiosqlite\core.py", line 132, in _execute
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1ea46b61460
```

**Comment by Finenyaco** [comment]
Verified on main af797cf
