### ISSUE TITLE
The worker is shut down after deleting an instance in the downloading state

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#690]
**Describe the bug**

**Steps to reproduce**

1. Deploy a model.
2. Delete the instance in downloading state.
3. View the server logs.

**Result**

1. The worker is shut down after deleting the instance.

```
2024-12-03T11:00:54+08:00 - gpustack.policies.scorers.placement_scorer - DEBUG - model stable-diffusion-xl-base-1.0, score canidates with ScaleTypeEnum.SCALE_UP placement policy, instance stable-diffusion-xl-base-1.0-GIkG2, model_instance: stable-diffusion-xl-base-1.0-GIkG2
2024-12-03T11:00:54+08:00 - gpustack.scheduler.scheduler - DEBUG - Pick highest score candidate from 1 candidates
2024-12-03T11:00:54+08:00 - gpustack.scheduler.scheduler - DEBUG - Scheduled model instance stable-diffusion-xl-base-1.0-GIkG2 to worker sealgpuhost4090 gpu [0]
2024-12-03T11:00:54+08:00 - gpustack.worker.serve_manager - INFO - Start serving model instance stable-diffusion-xl-base-1.0-GIkG2 on port 40330
2024-12-03T11:01:01+08:00 - gpustack.worker.logs - DEBUG - Reading logs from /Users/sophia/data/gpustack/log/serve/6.log with options LogOptions(tail=-1, follow=True)
2024-12-03T11:01:11+08:00 - gpustack.policies.scorers.placement_scorer - DEBUG - model paraformer-en, score instances with ScaleTypeEnum.SCALE_DOWN placement policy
2024-12-03T11:01:11+08:00 - gpustack.policies.scorers.offload_layer_scorer - DEBUG - model paraformer-en, score instances with offload layer policy
2024-12-03T11:01:11+08:00 - gpustack.policies.scorers.status_scorer - DEBUG - model paraformer-en, score instances with status policy
2024-12-03T11:01:11+08:00 - gpustack.server.controllers - DEBUG - Deleted model instance paraformer-en-MsY8O
2024-12-03T11:01:11+08:00 - gpustack.utils.signal - DEBUG - Received signal: 15. Shutting down gracefully...
ERROR:    Traceback (most recent call last):
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/anaconda3/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2024-12-03T11:01:11+08:00 - gpustack.worker.worker - INFO - Worker has shut down.
```

<img width="2284" alt="image" src="https://github.com/user-attachments/assets/1331b726-8ac8-4624-a5f8-5693489f3347">

**Environment**

- GPUStack version: main 28e5269
- OS: Ubuntu 22.04
- GPU: NVIDIA 4090

**Additional context**

**Comment by Finenyaco** [comment]
Verified on main faeb0cc
