### ISSUE TITLE
Returning error when chatting with Qwen2-VL model deployed by vLLM

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#785]
**Steps to reproduce**

1. Deploy model Hugging Face/Qwen/Qwen2-VL-2B
2. Chat in the playground

**Result**

1. `Internal server error: peer closed connection without sending complete message body (incomplete chunked read)`
<img width="2308" alt="image" src="https://github.com/user-attachments/assets/87b2573f-4496-48cf-8d7d-e955af0043a5" />

2. Check the instance logs.
```
INFO 12-13 16:02:45 logger.py:37] Received request chatcmpl-5ac4964460ba43039e93ab2a14fae40e: prompt: '', params: SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1024, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, guided_decoding=None), prompt_token_ids: None, lora_request: None, prompt_adapter_request: None.
INFO:     192.168.50.174:38158 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 12-13 16:02:45 preprocess.py:215] Your model uses the legacy input pipeline instead of the new multi-modal processor. Please note that the legacy pipeline will be removed in a future release. For more details, see: https://github.com/vllm-project/vllm/issues/10114
INFO 12-13 16:02:45 engine.py:285] Aborted request chatcmpl-5ac4964460ba43039e93ab2a14fae40e.
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 188, in __call__
  |     await response(scope, wrapped_receive, send)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 222, in __call__
  |     async for chunk in self.body_iterator:
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 179, in body_stream
  |     raise app_exc
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 149, in coro
  |     await self.app(scope, receive_or_disconnect, send_no_error)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/cors.py", line 144, in simple_response
  |     await self.app(scope, receive, send)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 252, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/home/seal/anaconda3/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
    |     await func()
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 244, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_chat.py", line 313, in chat_completion_stream_generator
    |     async for res in result_generator:
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/utils.py", line 402, in iterate_with_cancellation
    |     item = await awaits[0]
    |            ^^^^^^^^^^^^^^^
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 633, in _process_request
    |     raise request_output
    | AssertionError
    +------------------------------------
During handling of the above exception, another exception occurred:
  + Exception Group Traceback (most recent call last):
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 259, in __call__
    |     await wrap(partial(self.listen_for_disconnect, receive))
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
    |     await func()
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 232, in listen_for_disconnect
    |     message = await receive()
    |               ^^^^^^^^^^^^^^^
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 118, in receive_or_disconnect
    |     async with anyio.create_task_group() as task_group:
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 767, in __aexit__
    |     raise exc_val
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 126, in receive_or_disconnect
    |     message = await wrap(wrapped_receive)
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 121, in wrap
    |     result = await func()
    |              ^^^^^^^^^^^^
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 51, in wrapped_receive
    |     msg = await self.receive()
    |           ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 563, in receive
    |     await self.message_event.wait()
    |   File "/home/seal/anaconda3/lib/python3.11/asyncio/locks.py", line 213, in wait
    |     await fut
    | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7bb53b106810
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Exception Group Traceback (most recent call last):
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 188, in __call__
    |     await response(scope, wrapped_receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 222, in __call__
    |     async for chunk in self.body_iterator:
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 179, in body_stream
    |     raise app_exc
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    |     await self.simple_response(scope, receive, send, request_headers=headers)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    |     await self.app(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    |     await response(scope, receive, send)
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 252, in __call__
    |     async with anyio.create_task_group() as task_group:
    |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
    |     raise BaseExceptionGroup(
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
      |     result = await app(  # type: ignore[func-returns-value]
      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
      |     return await self.app(scope, receive, send)
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
      |     await super().__call__(scope, receive, send)
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
      |     await self.middleware_stack(scope, receive, send)
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
      |     raise exc
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
      |     await self.app(scope, receive, _send)
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 185, in __call__
      |     with collapse_excgroups():
      |   File "/home/seal/anaconda3/lib/python3.11/contextlib.py", line 158, in __exit__
      |     self.gen.throw(typ, value, traceback)
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
      |     raise exc
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
      |     await func()
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 244, in stream_response
      |     async for chunk in self.body_iterator:
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_chat.py", line 313, in chat_completion_stream_generator
      |     async for res in result_generator:
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/utils.py", line 402, in iterate_with_cancellation
      |     item = await awaits[0]
      |            ^^^^^^^^^^^^^^^
      |   File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 633, in _process_request
      |     raise request_output
      | AssertionError
      +------------------------------------
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/home/seal/anaconda3/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
    await func()
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 244, in stream_response
    async for chunk in self.body_iterator:
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_chat.py", line 313, in chat_completion_stream_generator
    async for res in result_generator:
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/utils.py", line 402, in iterate_with_cancellation
    item = await awaits[0]
           ^^^^^^^^^^^^^^^
  File "/home/seal/.local/share/pipx/venvs/gpustack/lib/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 633, in _process_request
    raise request_output
AssertionError
```

**Environment**

- GPUStack version: v0.4.1rc1
- OS: Ubuntu 22.04
- GPU: NVIDIA 4090

**Additional context**

**Comment by gitlawr** [comment]
It's not in supported models of vLLM.
use `Qwen/Qwen2-VL-2B-Instruct` instead

https://docs.vllm.ai/en/stable/models/supported_models.html
