### ISSUE TITLE
Incorrect vLLM tensor-parallel-size calculated by auto scheduling and cause inference engine error

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#814]
**Describe the bug**
Incorrect vLLM tensor-parallel-size calculated by auto-scheduling and causes inference engine error 

**Steps to reproduce**

In an A800x4 environment, try to deploy ModelScope/OpenGVLab/InternVL2_5-78B-AWQ with --trust-remote-code, --quantization=awq. The auto schedule will use 3 GPUs for parallelism, which is not supported by vLLM.

**Result**

vLLM will exit with error: 
```
RROR 12-18 19:47:34 engine.py:366] ValueError: Total number of attention heads (64) must be divisible by tensor parallel size (3).
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 368, in run_mp_engine
    raise e
  File "/opt/conda/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 114, in from_engine_args
    engine_config = engine_args.create_engine_config()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 1143, in create_engine_config
    return VllmConfig(
           ^^^^^^^^^^^
  File "<string>", line 15, in __init__
  File "/opt/conda/lib/python3.11/site-packages/vllm/config.py", line 2120, in __post_init__
    self.model_config.verify_with_parallel_config(self.parallel_config)
  File "/opt/conda/lib/python3.11/site-packages/vllm/config.py", line 530, in verify_with_parallel_config
    raise ValueError(
ValueError: Total number of attention heads (64) must be divisible by tensor parallel size (3).
```

**Expected behavior**

Correct parallelism size 4 should be used. 

**Environment**

- GPUStack version: v0.4.1
- OS: Linux
- GPU: A800

**Comment by pengjiang80** [comment]
Different models may have different numbers of attention heads. We must detect the correct head number and choose the proper parallelism number.

**Comment by Finenyaco** [comment]
Verified in main 5101502
