### ISSUE TITLE
Support using PostgreSQL as the datastore

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#85]

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(07aa6aa)
- OS: macOS 15.1
- GPU: Apple M2

**Test Result:**
1. Install GPUStack using postgresql as datastore.
2.Deploy a model and then go the dashboard. It reported an internal server error.

<img width="2306" alt="image" src="https://github.com/user-attachments/assets/b3ae2fd9-ab52-4c22-883d-84e0ca3ed38f">

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 534, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 207, in bind_execute
asyncpg.exceptions.NumericValueOutOfRangeError: value "2348357632" is out of range for type integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 546, in _prepare_and_execute
    self._handle_exception(error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 497, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.NumericValueOutOfRangeError'>: value "2348357632" is out of range for type integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.pyenv/versions/3.12.7/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 212, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.pyenv/versions/3.12.7/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 37, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.pyenv/versions/3.12.7/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/api/middlewares.py", line 31, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/routes/dashboard.py", line 39, in dashboard
    active_models = await get_active_models(session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/routes/dashboard.py", line 215, in get_active_models
    results = (await session.exec(statement)).all()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlmodel/ext/asyncio/session.py", line 83, in exec
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlmodel/orm/session.py", line 68, in exec
    results = super().execute(
              ^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 546, in _prepare_and_execute
    self._handle_exception(error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 497, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.NumericValueOutOfRangeError'>: value "2348357632" is out of range for type integer
[SQL: SELECT models.id, models.name, count(DISTINCT model_instances.id) AS instance_count, coalesce(resource_claim.total_ram_claim, $1::INTEGER) AS total_ram_claim, coalesce(resource_claim.total_vram_claim, $2::INTEGER) AS total_vram_claim, usage_sum.total_token_count
FROM models JOIN model_instances ON models.id = model_instances.model_id LEFT OUTER JOIN (SELECT model_instances.model_id AS model_id, sum(coalesce(CAST(json_extract_path_text(model_instances.computed_resource_claim, $3::VARCHAR) AS INTEGER), $4::INTEGER)) AS total_ram_claim, sum(coalesce(CAST(anon_1.value AS INTEGER), $5::INTEGER)) AS total_vram_claim
FROM model_instances, json_each_text(model_instances.computed_resource_claim -> $6::TEXT) AS anon_1 GROUP BY model_instances.model_id) AS resource_claim ON models.id = resource_claim.model_id LEFT OUTER JOIN (SELECT models.id AS model_id, sum(model_usages.prompt_token_count + model_usages.completion_token_count) AS total_token_count
FROM models LEFT OUTER JOIN model_usages ON models.id = model_usages.model_id GROUP BY models.id) AS usage_sum ON models.id = usage_sum.model_id GROUP BY models.id, usage_sum.total_token_count, resource_claim.total_ram_claim, resource_claim.total_vram_claim ORDER BY usage_sum.total_token_count DESC
 LIMIT $7::INTEGER]
[parameters: (0, 0, 'ram', 0, 0, 'vram', 10)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)

```

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(4d90845)
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4080 SUPER

**Test Result:**

Deploy models from ModelScope: pass

<img width="2080" alt="image" src="https://github.com/user-attachments/assets/800f3641-ef26-452a-a233-6b0e6140a39f">
