### ISSUE TITLE
The model instance has been stuck in Scheduled state

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#871]
**Describe the bug**

The model instance has been stuck in Scheduled state, and worker status is Ready.

**Steps to reproduce**

Try reconnecting after putting macOS to sleep.

**Result**

<img width="1300" alt="image" src="https://github.com/user-attachments/assets/a24f2ce7-e07e-4672-8511-e464f691ca04" />

**Environment**

- GPUStack version: v0.4.1
- OS: macOS
- GPU: M4

**Comment by linyinli** [comment]
It occurred even though the system was not in sleep.
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/cabf152b-5a37-4dd6-bc21-0d19f232259e" />

**Comment by pengjiang80** [comment]
Encountered this in the dev env with the 4080 host. The worker's status is ready, but the model is stuck in scheduled status. The log of the GPUStack worker container is as below:

```
2025-01-02T01:42:02+00:00 - gpustack.worker.worker - INFO - Starting GPUStack worker.
2025-01-02T01:42:02+00:00 - gpustack.worker.worker - INFO - Serving worker APIs on 0.0.0.0:10150.
2025-01-02T01:42:03+00:00 - gpustack.worker.worker_manager - INFO - Registering worker: sealgpuhost4080
2025-01-02T01:42:03+00:00 - gpustack.worker.worker_manager - INFO - Worker sealgpuhost4080 registered.
2025-01-02T01:42:03+00:00 - gpustack.worker.exporter - INFO - Serving metric exporter on 0.0.0.0:10151.
2025-01-02T01:42:05+00:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50231, pid 47
2025-01-02T01:42:05+00:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 1 on port 50293, pid 48
2025-01-02T01:49:09+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-7b-instruct-mKQry on port 40756
2025-01-02T01:49:36+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance bge-reranker-v2-m3-nMXSA on port 40796
2025-01-02T01:49:56+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance cosyvoice-300m-sft-tfAed on port 40358
2025-01-02T01:50:07+00:00 - modelscope - INFO - Download model 'gpustack/bge-reranker-v2-m3-GGUF' successfully.
2025-01-02T01:50:57+00:00 - modelscope - INFO - Download model 'iic/CosyVoice-300M-SFT' successfully.
2025-01-02T06:49:43+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-vllm-QLL3X on port 40870
pipx >(setup:1108): 2025-01-02 06:49:46
pipx >(setup:1109): /usr/local/bin/pipx install -vv --force --suffix _v0.6.6.post1 vllm==v0.6.6.post1
pipx >(setup:1110): pipx version is 1.7.1
pipx >(setup:1111): Default python interpreter is '/usr/bin/python3.10'
pipx >(package_name_from_spec:378): Determined package name: vllm
pipx >(package_name_from_spec:379): Package name determined in 0.0s
pipx >(create_venv:164): Creating virtual environment
creating virtual environment...
pipx >(run_subprocess:175): running /usr/bin/python3.10 -m venv --without-pip /root/.local/share/pipx/venvs/vllm-v0-6-6-post1
pipx >(run_subprocess:195): stdout:
pipx >(run_subprocess:197): stderr:
pipx >(run_subprocess:198): returncode: 0
creating shared libraries...
pipx >(run_subprocess:175): running /usr/bin/python3.10 -m venv --clear /root/.local/share/pipx/shared
pipx >(run_subprocess:195): stdout: The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /root/.local/share/pipx/shared/bin/python3.10
pipx >(run_subprocess:197): stderr:
pipx >(run_subprocess:198): returncode: 1
pipx >(rmdir:56): removing directory /root/.local/share/pipx/venvs/vllm-v0-6-6-post1
'/usr/bin/python3.10 -m venv --clear /root/.local/share/pipx/shared' failed
pipx >(cli:1179): PipxError: '/usr/bin/python3.10 -m venv --clear /root/.local/share/pipx/shared' failed
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pipx/main.py", line 1176, in cli
    return run_pipx_command(parsed_pipx_args, subparsers)
  File "/usr/local/lib/python3.10/dist-packages/pipx/main.py", line 282, in run_pipx_command

    apt install python3.10-venv

    return commands.install(
  File "/usr/local/lib/python3.10/dist-packages/pipx/commands/install.py", line 96, in install
    venv.create_venv(venv_args, pip_args, override_shared)
You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

  File "/usr/local/lib/python3.10/dist-packages/pipx/venv.py", line 172, in create_venv
    shared_libs.create(verbose=self.verbose, pip_args=pip_args)
  File "/usr/local/lib/python3.10/dist-packages/pipx/shared_libs.py", line 66, in create
    subprocess_post_check(create_process)
  File "/usr/local/lib/python3.10/dist-packages/pipx/util.py", line 210, in subprocess_post_check
    raise PipxError(f"{' '.join([str(x) for x in completed_process.args])!r} failed")
Failing command: /root/.local/share/pipx/shared/bin/python3.10


pipx.util.PipxError: '/usr/bin/python3.10 -m venv --clear /root/.local/share/pipx/shared' failed
pipx >(cli:1187): pipx finished.
2025-01-02T11:47:33+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2-vl-7b-instruct-qh7nO on port 40131
2025-01-02T16:12:07+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-Aq97s on port 40731
2025-01-02T16:12:07+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-Uaz4T on port 40634
2025-01-02T16:12:26+00:00 - modelscope - INFO - Download model 'Qwen/Qwen2.5-0.5B-Instruct-GGUF' successfully.
2025-01-02T16:12:26+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:12:26+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:12:27+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:12:27+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:12:45+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-GHDi3 on port 40916
2025-01-02T16:12:48+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-jLDiK on port 40989
2025-01-02T16:12:49+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:12:49+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:12:52+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:12:52+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:13:05+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-Hl5zI on port 40347
2025-01-02T16:13:06+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-rxq0s on port 40496
2025-01-02T16:13:09+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:13:09+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:13:10+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:13:10+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:13:13+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-pLxHR on port 40410
2025-01-02T16:13:14+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-Kx1GB on port 40528
2025-01-02T16:13:17+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:13:17+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:13:18+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:13:18+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:14:13+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-B463A on port 40076
2025-01-02T16:14:13+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-test-PlCoI on port 40489
2025-01-02T16:14:17+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:14:17+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-02T16:14:18+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-02T16:14:18+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-03T07:49:28+00:00 - gpustack.worker.serve_manager - INFO - Start serving model instance qwen2.5-0.5b-instruct-O8EYa on port 40842
2025-01-03T07:53:00+00:00 - modelscope - INFO - Download model 'Qwen/Qwen2.5-0.5B-Instruct-GGUF' successfully.
2025-01-03T07:53:00+00:00 - modelscope - INFO - Creating symbolic link [/var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF].
2025-01-03T07:53:00+00:00 - modelscope - WARNING - Failed to create symbolic link /var/lib/gpustack/cache/model_scope/hub/Qwen/Qwen2.5-0.5B-Instruct-GGUF.
2025-01-03T08:15:44+00:00 - gpustack.worker.collector - ERROR - Failed to inject allocated resources: [Errno 113] No route to host
2025-01-03T08:15:47+00:00 - gpustack.worker.worker_manager - ERROR - Failed to update status for worker sealgpuhost4080: [Errno 113] No route to host
2025-01-03T08:16:19+00:00 - gpustack.worker.collector - ERROR - Failed to inject allocated resources: [Errno 113] No route to host
2025-01-03T08:16:22+00:00 - gpustack.worker.worker_manager - ERROR - Failed to update status for worker sealgpuhost4080: [Errno 113] No route to host
```

Go to the shell of the GPUStack container, try to curl the GPUStack server, the access is normal.
```
➜ docker exec -it 5b bash
root@sealgpuhost4080:/# curl http://192.168.50.4
<!DOCTYPE html>
<html data-env="production" data-version="b16ae64">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="/static/favicon.png">
<link rel="stylesheet" href="/css/umi.1734086625008.css">

</head>
<body>
<div id="root"></div>
<script src="/js/umi.1734086625008.js"></script>
</body>
```

**Comment by Finenyaco** [comment]
Verified in main 51cab64 and unable to reproduce. Closing it for now. Feel free to reopen if the issue persists or can be reproduced.

**Comment by pengjiang80** [comment]
Not resolved. Besides the two occurrence above, still happening in local 4080 dev environment in v0.5.1

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/26602f3e-90d2-4df4-9ec0-76f6f4ddffa0" />

**Comment by gitlawr** [comment]
A timing issue that could happen when the worker starts watching before it is registered. The exception is not handled properly so the watch ends on the worker side.

The workaround in v0.5.1 is to restart the worker that enters this state.

**Comment by Finenyaco** [comment]
Verified on main cfb6481
