### ISSUE TITLE
Failed to get instance log when the worker-port of server and worker is inconsistent

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#90]
**Describe the bug**

Failed to get instance log when the Windows host acts as a worker.

**Steps to reproduce**

1. Run gpustack  server and add a Windows host as a worker.
2. Deploy a model to the worker.
3. Check the instance logs.

**Result**

1. Failed to get logs.
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/8b8bbe17-feff-4941-ad96-4645dc892d0e">

2. Go to the Windows host and check the logs.
<img width="1645" alt="image" src="https://github.com/user-attachments/assets/91a65fba-64c9-4116-9197-757409f779fe">

3. Check the server logs.
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/sophia/miniconda3/envs/gpustack-qa/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/sophia/miniconda3/envs/gpustack-qa/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 217, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    async for chunk in self.body_iterator:
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in body_stream
    raise app_exc
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/sophia/miniconda3/envs/gpustack-qa/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    async for chunk in self.body_iterator:
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/gpustack/routes/model_instances.py", line 94, in proxy_stream
    async with client.stream(
  File "/Users/sophia/miniconda3/envs/gpustack-qa/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_client.py", line 1617, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/Users/sophia/miniconda3/envs/gpustack-qa/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sophia/.local/pipx/venvs/gpustack/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
```

**Expected behavior**

1. Display the logs.

**Environment**

- GPUStack version: main(a9cb7f5)
- OS: 
-- Server: MacOS 14.2.1
-- Worker: Windows 11
- GPU:
-- Server: Apple M2, 24G
-- Worker: NVIDIA GeForce RTX 4090 24G 

**Additional context**

**Comment by Finenyaco** [comment]
The issue arises due to the inconsistency in the ports between the two workers. After setting the worker ports to be the same, the errors no longer occur.

**Comment by Finenyaco** [comment]
Given that the server can obtain the worker's worker-port, the logs should also be viewable when the worker-port is inconsistent.

**Comment by Finenyaco** [comment]
Verified on main d469e71
